[phases.setup]
nixPkgs = ["...", "ffmpeg"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install --no-cache-dir torch==2.1.2+cpu torchaudio==2.1.2+cpu -f https://download.pytorch.org/whl/torch_stable.html",
    "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1"