[build]
builder = "nixpacks"
buildCommand = "./build.sh"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10